### ISSUE TITLE
hq-proxies.yml中的redis的db名称怎么设置

### ISSUE THREAD

**Issue by x7peeps** [arthurmmm/hq-proxies#1]
我的redis使用的db0, 
set name "hq_proxies_db";

但是我在配置hq-proxies.yml的时候在REDIS_DB一项不论输入hq_proxies_db还是输入db0.都会报错：
2017-08-19 09:22:30,814 20/126: 启动进程中...
Traceback (most recent call last):
  File "start.py", line 178, in <module>
    main()
  File "start.py", line 128, in main
    redis_db.delete(PROXY_PROTECT)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 841, in delete
    return self.execute_command('DEL', *names)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 520, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: invalid DB index

**Comment by x7peeps** [comment]
```bash
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_PASSWORD: "123456"
REDIS_DB: "db0"

#Redis key 
PROXY_COUNT: hq-proxies:proxy_count
PROXY_SET: hq-proxies:proxy_pool
PROXY_PROTECT: hq-proxies:proxy_protect
PROXY_REFRESH: hq-proxies:proxy_refresh
```

**Comment by x7peeps** [comment]
已经解决了(— —~!)3   查了一下python链接redis的代码
```bash

        There are several ways to specify a database number. The parse function
        will return the first specified option:
            1. A ``db`` querystring option, e.g. redis://localhost?db=0
            2. If using the redis:// scheme, the path argument of the url, e.g.
               redis://localhost/0
            3. The ``db`` argument to this function.

        If none of these options are specified, db=0 is used.

        The ``decode_components`` argument allows this function to work with
        percent-encoded URLs. If this argument is set to ``True`` all ``%xx``
        escapes will be replaced by their single-character equivalents after
        the URL has been parsed. This only applies to the ``hostname``,
        ``path``, and ``password`` components.

        Any additional querystring arguments and keyword arguments will be
        passed along to the ConnectionPool class's initializer. In the case
        of conflicting arguments, querystring arguments always win.
        """
```
其中看到REDIS_DB的值应该只是一个数字了。。
于是改成
```bash 
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_PASSWORD: "123456"
REDIS_DB:  0
```
成功了(— v —)223

**Comment by arthurmmm** [comment]
👏
最近比较忙还感冒了没来得及看你的问题，不好意思哈~

**Comment by x7peeps** [comment]
老板issue新加了一个，麻烦有空给看下，我那问题出在哪了。现在爬不出来代理。
